#!/bin/bash

# =============================================================================
# Pull Environment Variables from Railway for Local Development
# =============================================================================
# This script pulls environment variables from Railway and creates a .env file
# for local development.
#
# Usage:
#   chmod +x scripts/pull-env-from-railway.sh
#   ./scripts/pull-env-from-railway.sh
# =============================================================================

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

echo -e "${BLUE}=====================================================${NC}"
echo -e "${BLUE}  Pull Environment Variables from Railway${NC}"
echo -e "${BLUE}=====================================================${NC}"
echo ""

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo -e "${RED}Error: Railway CLI is not installed${NC}"
    echo "Install it from: https://docs.railway.app/develop/cli"
    exit 1
fi

# Check if project is linked
if ! railway status &> /dev/null; then
    echo -e "${YELLOW}Project not linked. Attempting to link...${NC}"
    echo "Please run: railway link -p 8f6a7da7-ccc0-49b7-ba09-cc932b93d39b"
    exit 1
fi

echo -e "${GREEN}✓ Railway CLI found${NC}"
echo -e "${GREEN}✓ Project is linked${NC}"
echo ""

# Check if service is linked
if ! railway service &> /dev/null; then
    echo -e "${YELLOW}Warning: No service linked. You may need to link a service first.${NC}"
    echo -e "${YELLOW}Run: railway service${NC}"
    echo ""
fi

# Create backup of existing .env if it exists
if [ -f "$ENV_FILE" ]; then
    BACKUP_FILE="${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${YELLOW}Backing up existing .env to: $BACKUP_FILE${NC}"
    cp "$ENV_FILE" "$BACKUP_FILE"
    echo ""
fi

# Start creating .env file
echo -e "${BLUE}Creating .env file...${NC}"
echo ""

# Write header
cat > "$ENV_FILE" << 'EOF'
# =============================================================================
# Environment Variables for Local Development
# =============================================================================
# This file was generated by scripts/pull-env-from-railway.sh
# DO NOT commit this file to version control (it's in .gitignore)
#
# To pull fresh variables from Railway:
#   ./scripts/pull-env-from-railway.sh
# =============================================================================

EOF

# Add Redis URL from Services.md (known value)
echo -e "${GREEN}Adding Redis URL from Services.md...${NC}"
cat >> "$ENV_FILE" << 'EOF'
# Redis Configuration (from Services.md)
REDIS_URL=redis://default:YjxVPvvpKLskUcKvusxcIFrgaPRgQCPF@shortline.proxy.rlwy.net:40311

EOF

# Try to get variables from Railway (if service is linked)
echo -e "${BLUE}Attempting to pull variables from Railway...${NC}"
echo -e "${YELLOW}Note: You may need to link a service first with: railway service${NC}"
echo ""

# Try to get variables using Railway CLI
# Note: This may require service to be linked
if railway variables --json &> /dev/null; then
    echo -e "${GREEN}Pulling variables from Railway...${NC}"
    railway variables --json | python3 -c "
import json
import sys

try:
    data = json.load(sys.stdin)
    if isinstance(data, dict) and 'variables' in data:
        vars_list = data['variables']
    elif isinstance(data, list):
        vars_list = data
    else:
        vars_list = []
    
    for var in vars_list:
        if isinstance(var, dict):
            key = var.get('name', '')
            value = var.get('value', '')
            if key and value:
                print(f'{key}={value}')
except Exception as e:
    print(f'# Error parsing Railway variables: {e}', file=sys.stderr)
    sys.exit(1)
" >> "$ENV_FILE" 2>/dev/null || echo -e "${YELLOW}Could not pull variables from Railway (service may not be linked)${NC}"
else
    echo -e "${YELLOW}Could not pull variables from Railway${NC}"
    echo -e "${YELLOW}You can manually add variables to .env or link a service with: railway service${NC}"
fi

echo ""

# Add common optional variables as comments
cat >> "$ENV_FILE" << 'EOF'

# Optional: Proxy Configuration
# WEBSHARE_PROXY_USERNAME=your-username
# WEBSHARE_PROXY_PASSWORD=your-password

# Optional: AI Features (OpenRouter)
# OPENROUTER_API_KEY=your-api-key

# Optional: Cache Configuration
# CACHE_TTL_SECONDS=3600

# Server Configuration (defaults)
# HOST=0.0.0.0
# PORT=8000

# Logging Configuration
# LOG_LEVEL=INFO
# JSON_LOGS=false

EOF

echo -e "${GREEN}✓ .env file created at: $ENV_FILE${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo -e "  1. Review the .env file and add any missing variables"
echo -e "  2. Add sensitive variables manually if needed"
echo -e "  3. Test the server: ${YELLOW}uv run main.py${NC}"
echo -e "  4. Run tests: ${YELLOW}./scripts/test_endpoints.sh${NC}"
echo ""
echo -e "${GREEN}Done!${NC}"
